//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/parser/DocumentI.java
//


#include "J2ObjC_source.h"
#include "DocumentI.h"
#include "ElementI.h"
#include "Element.h"
#include "org/w3c/dom/Document.h"
#include "org/w3c/dom/Element.h"

@interface DocumentI () {
 @public
  id<OrgW3cDomDocument> impl_;
}

@end

J2OBJC_FIELD_SETTER(DocumentI, impl_, id<OrgW3cDomDocument>)

@implementation DocumentI

- (instancetype)initWithOrgW3cDomDocument:(id<OrgW3cDomDocument>)impl {
  DocumentI_initWithOrgW3cDomDocument_(self, impl);
  return self;
}

- (id<OrgScilabForgeJlatexmathPlatformParserElement>)getDocumentElement {
  return new_ElementI_initWithOrgW3cDomElement_([((id<OrgW3cDomDocument>) nil_chk(impl_)) getDocumentElement]);
}

@end

void DocumentI_initWithOrgW3cDomDocument_(DocumentI *self, id<OrgW3cDomDocument> impl) {
  (void) NSObject_init(self);
  self->impl_ = impl;
}

DocumentI *new_DocumentI_initWithOrgW3cDomDocument_(id<OrgW3cDomDocument> impl) {
  DocumentI *self = [DocumentI alloc];
  DocumentI_initWithOrgW3cDomDocument_(self, impl);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DocumentI)
