//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/parser/NamedNodeMapI.java
//


#include "J2ObjC_source.h"
#include "NamedNodeMapI.h"
#include "NodeI.h"
#include "Node.h"
#include "org/w3c/dom/NamedNodeMap.h"
#include "org/w3c/dom/Node.h"

@interface NamedNodeMapI () {
 @public
  id<OrgW3cDomNamedNodeMap> impl_;
}

@end

J2OBJC_FIELD_SETTER(NamedNodeMapI, impl_, id<OrgW3cDomNamedNodeMap>)

@implementation NamedNodeMapI

- (instancetype)initWithOrgW3cDomNamedNodeMap:(id<OrgW3cDomNamedNodeMap>)impl {
  NamedNodeMapI_initWithOrgW3cDomNamedNodeMap_(self, impl);
  return self;
}

- (jint)getLength {
  return [((id<OrgW3cDomNamedNodeMap>) nil_chk(impl_)) getLength];
}

- (id<OrgScilabForgeJlatexmathPlatformParserNode>)itemWithInt:(jint)index {
  return new_NodeI_initWithOrgW3cDomNode_([((id<OrgW3cDomNamedNodeMap>) nil_chk(impl_)) itemWithInt:index]);
}

@end

void NamedNodeMapI_initWithOrgW3cDomNamedNodeMap_(NamedNodeMapI *self, id<OrgW3cDomNamedNodeMap> impl) {
  (void) NSObject_init(self);
  self->impl_ = impl;
}

NamedNodeMapI *new_NamedNodeMapI_initWithOrgW3cDomNamedNodeMap_(id<OrgW3cDomNamedNodeMap> impl) {
  NamedNodeMapI *self = [NamedNodeMapI alloc];
  NamedNodeMapI_initWithOrgW3cDomNamedNodeMap_(self, impl);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(NamedNodeMapI)
