//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/parser/NodeListI.java
//


#include "J2ObjC_source.h"
#include "NodeI.h"
#include "NodeListI.h"
#include "Node.h"
#include "org/w3c/dom/Node.h"
#include "org/w3c/dom/NodeList.h"

@interface NodeListI () {
 @public
  id<OrgW3cDomNodeList> impl_;
}

@end

J2OBJC_FIELD_SETTER(NodeListI, impl_, id<OrgW3cDomNodeList>)

@implementation NodeListI

- (instancetype)initWithOrgW3cDomNodeList:(id<OrgW3cDomNodeList>)impl {
  NodeListI_initWithOrgW3cDomNodeList_(self, impl);
  return self;
}

- (jint)getLength {
  return [((id<OrgW3cDomNodeList>) nil_chk(impl_)) getLength];
}

- (id<OrgScilabForgeJlatexmathPlatformParserNode>)itemWithInt:(jint)index {
  return new_NodeI_initWithOrgW3cDomNode_([((id<OrgW3cDomNodeList>) nil_chk(impl_)) itemWithInt:index]);
}

@end

void NodeListI_initWithOrgW3cDomNodeList_(NodeListI *self, id<OrgW3cDomNodeList> impl) {
  (void) NSObject_init(self);
  self->impl_ = impl;
}

NodeListI *new_NodeListI_initWithOrgW3cDomNodeList_(id<OrgW3cDomNodeList> impl) {
  NodeListI *self = [NodeListI alloc];
  NodeListI_initWithOrgW3cDomNodeList_(self, impl);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(NodeListI)
