//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/platform/parser/Attr.java
//


#include "Attr.h"
#include "J2ObjC_source.h"

@interface OrgScilabForgeJlatexmathPlatformParserAttr : NSObject
@end

@implementation OrgScilabForgeJlatexmathPlatformParserAttr


}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathPlatformParserAttr)
