//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/platform/parser/Document.java
//


#include "Document.h"
#include "Element.h"
#include "J2ObjC_source.h"

@interface OrgScilabForgeJlatexmathPlatformParserDocument : NSObject
@end

@implementation OrgScilabForgeJlatexmathPlatformParserDocument


@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathPlatformParserDocument)
