//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/platform/parser/Element.java
//


#include "Element.h"
#include "J2ObjC_source.h"
#include "NamedNodeMap.h"
#include "NodeList.h"

@interface OrgScilabForgeJlatexmathPlatformParserElement : NSObject
@end

@implementation OrgScilabForgeJlatexmathPlatformParserElement


@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathPlatformParserElement)
