//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/platform/parser/NamedNodeMap.java
//


#include "J2ObjC_source.h"
#include "NamedNodeMap.h"
#include "Node.h"

@interface OrgScilabForgeJlatexmathPlatformParserNamedNodeMap : NSObject
@end


@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathPlatformParserNamedNodeMap)
