//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/platform/parser/Node.java
//


#include "Attr.h"
#include "Element.h"
#include "J2ObjC_source.h"
#include "Node.h"

@interface OrgScilabForgeJlatexmathPlatformParserNode : NSObject
@end

@implementation OrgScilabForgeJlatexmathPlatformParserNode


@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathPlatformParserNode)
