//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/platform/parser/NodeList.java
//


#include "J2ObjC_source.h"
#include "Node.h"
#include "NodeList.h"

@interface OrgScilabForgeJlatexmathPlatformParserNodeList : NSObject
@end

@implementation OrgScilabForgeJlatexmathPlatformParserNodeList


@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathPlatformParserNodeList)
