//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/platform/parser/ParserFactory.java
//


#include "J2ObjC_source.h"
#include "Parser.h"
#include "ParserFactory.h"

@implementation OrgScilabForgeJlatexmathPlatformParserParserFactory

- (id<OrgScilabForgeJlatexmathPlatformParserParser>)createParser {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (instancetype)init {
  OrgScilabForgeJlatexmathPlatformParserParserFactory_init(self);
  return self;
}


@end

void OrgScilabForgeJlatexmathPlatformParserParserFactory_init(OrgScilabForgeJlatexmathPlatformParserParserFactory *self) {
  (void) NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathPlatformParserParserFactory)
