//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/platform/parser/Parser.java
//


#include "Document.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "Parser.h"
#include "ResourceParseException.h"

@interface OrgScilabForgeJlatexmathPlatformParserParser : NSObject
@end

@implementation OrgScilabForgeJlatexmathPlatformParserParser


@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathPlatformParserParser)
